# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# SEO Tag
title: Gurpreet's Portfolio
email: gurupreetsingh2000@gmail.com
author: Gurpreet Singh
description: >- # this means to ignore newlines until "baseurl:"
  I'm Gurpreet Singh, a Web Architect based in Frankfurt. Take a look at my portfolio!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.gsin.in" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gsin11
github_username:  gsin11

google_analytics: UA-ASDAS

permalink: /:title/

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag

# Footer
footer:
    - text: Email
      url: mailto:gurupreetsingh2000@gmail.com
      icon: icon-mail-inline
    - text: Resume
      url: /assets/downloads/resume-gurpreet-singh.pdf
      icon: icon-cv-inline
    - text: LinkedIn
      url: https://www.linkedin.com/in/gsin11/
      icon: icon-linkedin

# Navigation links
navigation:
    - title: Home
      url: /
    - title: Resume
      url: /assets/downloads/resume-gurpreet-singh.pdf
    - title: Contact
      url: mailto:gurupreetsingh2000@gmail.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
---